// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tel.Egram.Services.Persistence;

#nullable disable

namespace Tel.Egram.Services.Persistence.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250430204601_Migr1")]
    partial class Migr1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Tel.Egram.Services.Persistence.Entities.KeyValueEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("key_value", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
