<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.2.8" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.2.8" />
        <PackageReference Include="Avalonia.ReactiveUI" Version="11.2.8" />
    </ItemGroup>
    
    <ItemGroup>
        <AvaloniaResource Include="Icons\**\*" />
        <AvaloniaResource Include="**\*.xaml">
            <SubType>Designer</SubType>
        </AvaloniaResource>
    </ItemGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\Tel.Egram.ViewModels\Tel.Egram.ViewModels.csproj" />
    </ItemGroup>
    
</Project>